// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForBulkInsertUnits implements pgx.CopyFromSource.
type iteratorForBulkInsertUnits struct {
	rows                 []BulkInsertUnitsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertUnits) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertUnits) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Unitname,
		r.rows[0].Starlevel,
		r.rows[0].Items,
		r.rows[0].Placement,
	}, nil
}

func (r iteratorForBulkInsertUnits) Err() error {
	return nil
}

func (q *Queries) BulkInsertUnits(ctx context.Context, arg []BulkInsertUnitsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"units"}, []string{"unitname", "starlevel", "items", "placement"}, &iteratorForBulkInsertUnits{rows: arg})
}
