// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

type Unit struct {
	ID        int32
	Unitname  string
	Starlevel int16
	Items     []string
	Placement int16
}
