// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Unit struct {
	ID        int32
	Unitname  sql.NullString
	Starlevel sql.NullInt16
	Items     []string
	Placement sql.NullInt16
}
