// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: units.sql

package database

import (
	"context"
)

const insertUnit = `-- name: InsertUnit :one
INSERT INTO units(unitName, starLevel, items, placement)
VALUES ($1, $2, $3, $4)
RETURNING id, unitname, starlevel, items, placement
`

type InsertUnitParams struct {
	Unitname  string
	Starlevel int16
	Items     []string
	Placement int16
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, insertUnit,
		arg.Unitname,
		arg.Starlevel,
		arg.Items,
		arg.Placement,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Unitname,
		&i.Starlevel,
		&i.Items,
		&i.Placement,
	)
	return i, err
}
