// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: units.sql

package database

import (
	"context"
)

type BulkInsertUnitsParams struct {
	Unitname  string
	Starlevel int16
	Items     []string
	Placement int16
}

const insertUnit = `-- name: InsertUnit :exec
INSERT INTO units(unitName, starLevel, items, placement)
VALUES ($1, $2, $3, $4)
`

type InsertUnitParams struct {
	Unitname  string
	Starlevel int16
	Items     []string
	Placement int16
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) error {
	_, err := q.db.Exec(ctx, insertUnit,
		arg.Unitname,
		arg.Starlevel,
		arg.Items,
		arg.Placement,
	)
	return err
}
