// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: units.sql

package database

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const insertUnit = `-- name: InsertUnit :one
INSERT INTO units(id, unitName, starLevel, items, placement)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, unitname, starlevel, items, placement
`

type InsertUnitParams struct {
	ID        int32
	Unitname  sql.NullString
	Starlevel sql.NullInt16
	Items     []string
	Placement sql.NullInt16
}

func (q *Queries) InsertUnit(ctx context.Context, arg InsertUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, insertUnit,
		arg.ID,
		arg.Unitname,
		arg.Starlevel,
		pq.Array(arg.Items),
		arg.Placement,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.Unitname,
		&i.Starlevel,
		pq.Array(&i.Items),
		&i.Placement,
	)
	return i, err
}
