version: '3'
services:
  matchcrawler:
    build:
      context: ./matchCrawler
      dockerfile: ./Dockerfile
    env_file:
      - matchCrawler/.env
    volumes:
      - .:/matchcrawler
    depends_on:
      - migrations
      - queue
  
  queryapi:
    build:
      context: ./statsQueryApi
      dockerfile: ./Dockerfile
    env_file:
      - statsQueryApi/.env
    ports:
      - "8000:8000"
    volumes:
      - .:/queryapi
    depends_on:
      - migrations
    

  migrations:
    build:
      context: ./migrations
      dockerfile: ./Dockerfile
    volumes:
      - .:/migrations
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    ports:
      - "5432"
    volumes:
      - postgres-db:/database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  queue:
    image: redis
    restart: always
    ports:
      - "6379"
    volumes:
      - redis-queues:/queues


    

volumes:
  redis-queues:
  postgres-db: